export const formats = [
  {label: "MLA", value: 0},
  {label: "APA", value: 1},
  {label: "Chicago", value: 2},
  {label: "Harvard", value: 3},
  {label: "Turbian with Footnotes", value: 4},
  ];
export const services = [
  {label: "Academic Paper Writing", value: 0},
  {label: "Rewriting", value: 1},
  {label: "Math/Physic/Economic/Statistic Problems", value: 2},
  {label: "Proofreading", value: 3},
  {label: "Editing", value: 4},
  {label: "Copywriting", value: 5},
  {label: "Dissertation", value: 6},    
  ];
export const papers = [
  {label: "Essay", value: 0},
  {label: "Term Paper", value: 1},
  {label: "Research Paper", value: 2},
  {label: "Coursework", value: 3},
  {label: "Book Report", value: 4},
  {label: "Book Review", value: 5},
  {label: "Movie Review", value: 6},
  {label: "Research Summary", value: 7},
  {label: "Case Study", value: 8},
  {label: "Lab Report", value: 9},
  {label: "Powerpoint Presentation", value: 10},
  {label: "Artical", value: 11},
  {label: "Artical Critique", value: 12},
  {label: "Reaction Paper", value: 13},    
  ];
export const levels = [
  {label: "High School", value: 0},
  {label: "Freshman (College 1st year)", value: 1},
  {label: "Sophomore (College 2nd year)", value: 2},
  {label: "Junior (College 3rd year)", value: 3},
  {label: "Senior (College 4th year)", value: 4},  
  {label: "Master\'s", value: 5},
  {label: "Doctoral (PhD)", value: 6}
  ];
export const urgency = [
  {label: "9 hours", value: 0},
  {label: "12 hours", value: 1},
  {label: "18 hours", value: 2},
  {label: "24 hours", value: 3},
  {label: "3 days", value: 4},
  {label: "4 days", value: 5},
  {label: "5 days", value: 6},
  {label: "6 days", value: 7},
  {label: "7 days", value: 8},
  {label: "10 days", value: 9},
  {label: "14 days", value: 10}, 
  ];
export const prices = [
    { Urgency: '14 days', Price: `$12.99/page`, type: 'Academic Paper Writing' },
    { Urgency: '10 days', Price: '$15.99/page', type: 'Academic Paper Writing' },
    { Urgency: '7 days', Price: '$16.55/page', type: 'Academic Paper Writing' },
    { Urgency: '6 days', Price: '$16.99/page', type: 'Academic Paper Writing' },
    { Urgency: '5 days', Price: '$18.99/page', type: 'Academic Paper Writing' },
    { Urgency: '4 days', Price: '$19.99/page', type: 'Academic Paper Writing' },
    { Urgency: '3 days', Price: '$20.99/page', type: 'Academic Paper Writing' },
    { Urgency: '24 hours', Price: '$24.99/page', type: 'Academic Paper Writing' },
    { Urgency: '18 hours', Price: '$27.99/page', type: 'Academic Paper Writing' },
    { Urgency: '12 hours', Price: '$29.99/page', type: 'Academic Paper Writing' },
    { Urgency: '8 hours', Price: '$33.99/page', type: 'Academic Paper Writing' },
    { Urgency: '6 hours', Price: '$35.99/page', type: 'Academic Paper Writing' },
    { Urgency: '14 days', Price: '$9.99/page', type: 'Rewriting' },
    { Urgency: '10 days', Price: '$16.99/page', type: 'Rewriting' },
    { Urgency: '7 days', Price: '$17.55/page', type: 'Rewriting' },
    { Urgency: '6 days', Price: '$17.99/page', type: 'Rewriting' },
    { Urgency: '5 days', Price: '$18.55/page', type: 'Rewriting' },
    { Urgency: '4 days', Price: '$18.99/page', type: 'Rewriting' },
    { Urgency: '3 days', Price: '$19.99/page', type: 'Rewriting' },
    { Urgency: '24 hours', Price: '$24.99/page', type: 'Rewriting' },
    { Urgency: '18 hours', Price: '$27.99/page', type: 'Rewriting' },
    { Urgency: '12 hours', Price: '$29.99/page', type: 'Rewriting' },
    { Urgency: '8 hours', Price: '$31.99/page', type: 'Rewriting' },
    { Urgency: '6 hours', Price: '$35.99/page', type: 'Rewriting' },
    { Urgency: '14 days', Price: '$19.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '10 days', Price: '$20.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '7 days', Price: '$21.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '6 days', Price: '$22.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '5 days', Price: '$24.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '4 days', Price: '$26.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '3 days', Price: '$28.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '24 hours', Price: '$30.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '18 hours', Price: '$34.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '12 hours', Price: '$38.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '8 hours', Price: '$42.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '6 hours', Price: '$45.99/problem', type: 'Math/Physic/Economic/Statistic Problems' },
    { Urgency: '14 days', Price: '$4.99/page', type: 'Proofreading' },
    { Urgency: '10 days', Price: '$5.55/page', type: 'Proofreading' },
    { Urgency: '7 days', Price: '$5.99/page', type: 'Proofreading' },
    { Urgency: '6 days', Price: '$6.55/page', type: 'Proofreading' },
    { Urgency: '5 days', Price: '$6.99/page', type: 'Proofreading' },
    { Urgency: '4 days', Price: '$7.55/page', type: 'Proofreading' },
    { Urgency: '3 days', Price: '$8.55/page', type: 'Proofreading' },
    { Urgency: '24 hours', Price: '$10.99/page', type: 'Proofreading' },
    { Urgency: '18 hours', Price: '$12.99/page', type: 'Proofreading' },
    { Urgency: '12 hours', Price: '$14.99/page', type: 'Proofreading' },
    { Urgency: '8 hours', Price: '$16.99/page', type: 'Proofreading' },
    { Urgency: '6 hours', Price: '$18.99/page', type: 'Proofreading' },
    { Urgency: '14 days', Price: '$5.99/page', type: 'Editing' },
    { Urgency: '10 days', Price: '$6.99/page', type: 'Editing' },
    { Urgency: '7 days', Price: '$7.99/page', type: 'Editing' },
    { Urgency: '6 days', Price: '$8.99/page', type: 'Editing' },
    { Urgency: '5 days', Price: '$9.99/page', type: 'Editing' },
    { Urgency: '4 days', Price: '$10.99/page', type: 'Editing' },
    { Urgency: '3 days', Price: '$11.99/page', type: 'Editing' },
    { Urgency: '24 hours', Price: '$13.99/page', type: 'Editing' },
    { Urgency: '18 hours', Price: '$14.99/page', type: 'Editing' },
    { Urgency: '12 hours', Price: '$15.99/page', type: 'Editing' },
    { Urgency: '8 hours', Price: '$16.99/page', type: 'Editing' },
    { Urgency: '6 hours', Price: '$17.99/page', type: 'Editing' },
    { Urgency: '14 days', Price: '$24.99/page', type: 'Copywriting' },
    { Urgency: '10 days', Price: '$25.99/page', type: 'Copywriting' },
    { Urgency: '7 days', Price: '$27.99/page', type: 'Copywriting' },
    { Urgency: '6 days', Price: '$29.99/page', type: 'Copywriting' },
    { Urgency: '5 days', Price: '$31.99/page', type: 'Copywriting' },
    { Urgency: '4 days', Price: '$34.99/page', type: 'Copywriting' },
    { Urgency: '3 days', Price: '$36.99/page', type: 'Copywriting' },
    { Urgency: '24 hours', Price: '$42.99/page', type: 'Copywriting' },
    { Urgency: '18 hours', Price: '$46.99/page', type: 'Copywriting' },
    { Urgency: '12 hours', Price: '$50.99/page', type: 'Copywriting' },
    { Urgency: '8 hours', Price: '$55.99/page', type: 'Copywriting' },
    { Urgency: '6 hours', Price: '$60.99/page', type: 'Copywriting' },
    { Urgency: '14 days', Price: '$12.99/page', type: 'Dissertation' },
    { Urgency: '10 days', Price: '$15.99/page', type: 'Dissertation' },
    { Urgency: '7 days', Price: '$16.55/page', type: 'Dissertation' },
    { Urgency: '6 days', Price: '$16.99/page', type: 'Dissertation' },
    { Urgency: '5 days', Price: '$18.99/page', type: 'Dissertation' },
    { Urgency: '4 days', Price: '$19.99/page', type: 'Dissertation' },
    { Urgency: '3 days', Price: '$20.99/page', type: 'Dissertation' },
    { Urgency: '24 hours', Price: '$24.99/page', type: 'Dissertation' },
    { Urgency: '18 hours', Price: '$27.99/page', type: 'Dissertation' },
    { Urgency: '12 hours', Price: '$29.99/page', type: 'Dissertation' },
    { Urgency: '8 hours', Price: '$33.99/page', type: 'Dissertation' },
    { Urgency: '6 hours', Price: '$35.99/page', type: 'Dissertation' },
  ];
export const countries = ["Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo", "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia (Hrvatska)", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "East Timor", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France", "France Metropolitan", "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard and Mc Donald Islands", "Holy See (Vatican City State)", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran (Islamic Republic of)", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan", "Lao, People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia, The Former Yugoslav Republic of", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of", "Monaco", "Mongolia", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Seychelles", "Sierra Leone", "Singapore", "Slovakia (Slovak Republic)", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "St. Helena", "St. Pierre and Miquelon", "Sudan", "Suriname", "Svalbard and Jan Mayen Islands", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic", "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Virgin Islands (British)", "Virgin Islands (U.S.)", "Wallis and Futuna Islands", "Western Sahara", "Yemen", "Yugoslavia", "Zambia", "Zimbabwe"];

export const timeZones = [
  {label: "Pacific", value: 0},
  { label: "Mountain", value: 1}, 
  {label: "Central", value: 2}, 
  {label: "Eastern", value: 3}
]

//SendGrid
export const apikey = 'SG.iBiP5aoYQSeLxdXlGQFihg.jGmmDenQnHD2AUGas1ishGYfScbbdGgAQ3DKf1iAgCc';